<?php

namespace AppBundle\Repository;

/**
 * PlikiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlikiRepository extends \Doctrine\ORM\EntityRepository
{
}
